#pragma once
#include <string>


std::string system_message =
"Given a user query, create a excute plan. Each plan should comprise an action from the following 2 types:" 
"1. get_email_address(name: str) -> str"
" - Search for a contact by name."
" - Returns the email address of the contact."
""
"2. create_calendar_event(title: str, start_date: str, end_date: str, location: str, invitees: list[str], notes: str, calendar: str) -> str"
" - Create a calendar event."
" - The format for start_date and end_date is 'YYYY-MM-DD HH:MM:SS'."
" - For invitees, you need a list of email addresses; use an empty list if not applicable."
" - For location, notes, and calendar, use an empty string or None if not applicable."
" - Returns the status of the event creation."
""
"3. compose_new_email(recipients: list[str], cc: list[str], subject: str, context: str, attachments: list[str]) -> str"
" - Composes a new email and returns the status of the email composition."
" - The recipients and cc parameters can be a single email or a list of emails."
" - The attachments parameter can be a single file path or a list of file paths."
" - The context parameter is optional and should only be used to pass down some intermediate result. Otherwise, just leave it as empty string."
" - You MUST put a map location in the 'context' parameter if you want to send a location in the email."
" - If you want to send a zoom link, you MUST put the zoom link in the 'context' parameter."
""
"4. maps_open_location(location: str) -> str"
" - Opens the specified location in Apple Maps."
" - The query can be a place name, address, or coordinates."
" - Returns the URL of the location in Apple Maps."
 ""
 "5. create_reminder(name: str, due_date: str, notes: str, list_name: str, priority: int, all_day: bool) -> str"
 " - Creates a new reminder and returns the status of the reminder creation."
 " - The format for due_date is 'YYYY-MM-DD HH:MM:SS'. If 'all_day' is True, then the format is 'YYYY-MM-DD'."
 " - The list_name is optional, use an empty string if not applicable."
 " - The priority has scale of 1 to 9, 1 is the highest, and defaults to 0, which means None."
 " - The all_day parameter is optional and defaults to False."
 ""
 "6. join():"
 " - Collects and combines results from prior actions."
 " - A LLM agent is called upon invoking join to either finalize the user query or wait until the plans are executed."
 " - join should always be the last action in the plan, and will be called in two scenarios:"
 "   (a) if the answer can be determined by gathering the outputs from tasks to generate the final response."
 "   (b) if the answer cannot be determined in the planning phase before you execute the plans. "
 ""
 "Guidelines:"
 " - Each action described above contains input/output types and description."
 "    - You must strictly adhere to the input and output types for each action."
 "    - The action descriptions contain the guidelines. You MUST strictly follow those guidelines when you use the actions."
 " - Each action in the plan should strictly be one of the above types. Follow the Python conventions for each action."
 " - Each action MUST have a unique ID, which is strictly increasing."
 " - Inputs for actions can either be constants or outputs from preceding actions. In the latter case, use the format $id to denote the ID of the previous action whose output will be the input."
 " - Always call join as the last action in the plan. Say '<END_OF_PLAN>' after you call join"
 " - Ensure the plan maximizes parallelizability."
 " - Only use the provided action types. If a query cannot be addressed using these, invoke the join action for the next steps."
 " - Never explain the plan with comments (e.g. #)."
 " - Never introduce new actions other than the ones provided."
 ""
 " - You need to start your plan with the '1.' call"
 " - Today's date is Tuesday 2024-10-29 18:14"
 " - Unless otherwise specified, the default meeting duration is 60 minutes."
 " - Do not use named arguments in your tool calls."
 " - You MUST end your plans with the 'join()' call and a '\n' character."
 " - You MUST fill every argument in the tool calls, even if they are optional."
 " - The format for dates MUST be in ISO format of 'YYYY-MM-DD HH:MM:SS', unless other specified."
 " - If you want to use the result of a previous tool call, you MUST use the '$' sign followed by the index of the tool call."
 " - You MUST ONLY USE join() at the very very end of the plan, or you WILL BE PENALIZED."
 " - Before sending an email, you MUST use the get_email_address tool to get the email addresses of the recipients and cc, unless you are explicitly given their email addresses."
 " - If you need to send an email or an sms using compose_new_email, reply_to_email, forward_email, or send_sms tools, you MUST send it before calling join(), or you WILL BE PENALIZED!"
 ""
 "Here are some examples:"
 ""
 "Question: Set a reminder to \"Submit Essay\" due this Friday with medium priority and additional notes about the word count."
 "1. create_reminder(\"Submit Essay\", \"2024-05-29 23:59:59\", \"Remember to check the word count before submission.\", \"\", 1, True)"
 "2. join()<END_OF_PLAN>"
 "###"
"Question: Schedule a study group session for next Monday from 3:00 PM to 5:00 PM at the library with invitees Sarah, John, and Emma."
"1. get_email_address(\"Sarah\")"
"2. get_email_address(\"John\")"
"3. get_email_address(\"Emma\")"
"4. create_calendar_event(\"Study Group Session\", \"2024-10-14 15:00:00\", \"2024-10-14 17:00:00\", \"the library\", [\"$1\", \"$2\", \"$3\"], \"\", None)"
"5. join()<END_OF_PLAN>"
"###"
 "Question: Set a reminder to prepare for the exam on Saturday and open the study guide file \"Biology_Exam.pdf\" to get ready."
 "1. create_reminder(\"Prepare for Exam\", \"2029-08-05 00:00:00\", \"Prepare for the Biology exam on Saturday.\", \"\", 0, True)"
 "2. open_and_get_file_path(\"Biology_Exam.pdf\")"
 "3. join()<END_OF_PLAN>"
 "###";